### ISSUE TITLE
Failed running the deployment script

### ISSUE THREAD

**Issue by daniarherikurniawan** [Seagate/cortx-monitor#499]
I am following the most updated Readme here https://github.com/Seagate/cortx-monitor/blob/thavanathan-patch-1/cortx-monitorQuickstartGuide.md. I am using VM running on VMware Workstation installed in Seagate's laptop (has access to Seagate network). 

When following step #3 "Finally run the deployment script" : `$ ./sspl_dev_deploy --deploy -L /root/MYRPMS --variable_file ~/template_values.1-node.txt --storage_type RBOD --server_type HW`

I got this error:
```sh
=======================
INFO: Deploying SSPL...
=======================
INFO: Installing SSPL RPMS using yum repos...
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: repo.miserver.it.umich.edu
 * centos-sclo-sclo: ftpmirror.your.org
 * epel: mirror.genesisadaptive.com
 * extras: mirror.compevo.com
 * updates: ftpmirror.your.org
Nothing to do
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: repo.miserver.it.umich.edu
 * centos-sclo-sclo: ftpmirror.your.org
 * epel: mirror.genesisadaptive.com
 * extras: mirror.compevo.com
 * updates: ftpmirror.your.org
Nothing to do
INFO: Done installing SSPL RPMS.
INFO: Executing command: '/opt/seagate/cortx/utils/bin/utils_setup post_install --config yaml:///opt/seagate/cortx/sspl/conf/temp/post-install.1-node'
INFO: Executing command: '/opt/seagate/cortx/sspl/bin/sspl_setup post_install --config yaml:///opt/seagate/cortx/sspl/conf/temp/post-install.1-node'
INFO: Executing command: '/opt/seagate/cortx/sspl/bin/sspl_setup prepare --config yaml:///opt/seagate/cortx/sspl/conf/temp/prepare.1-node'
INFO: Executing command: '/opt/seagate/cortx/utils/bin/utils_setup config --config yaml:///opt/seagate/cortx/sspl/conf/temp/config.1-node'
INFO: Executing command: '/opt/seagate/cortx/sspl/bin/sspl_setup config --config yaml:///opt/seagate/cortx/sspl/conf/temp/config.1-node'
---DeployError---
ERROR: (22): Aug 11 19:31:41 sspl-setup[16077]: INFO config - Init done (sspl_setup:206) Aug 11 19:31:41 sspl-setup[16077]: INFO config - validation done (sspl_setup:227) Aug 11 19:31:56 sspl-setup[16077]: ERROR MessageBusError:error(4352): Admin operation fails for register_message_type. KafkaError{code=_TIMED_OUT,val=-185,str="Failed while waiting for controller: Local: Timed out"} (sspl_config.py:152) Traceback (most recent call last):   File "/usr/lib/python3.6/site-packages/cortx/utils/message_bus/message_broker_collection.py", line 156, in _task_status     task.result()  # The result itself is None   File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 432, in result     return self.__get_result()   File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 384, in __get_result     raise self._exception   File "/usr/local/lib64/python3.6/site-packages/confluent_kafka/admin/__init__.py", line 225, in _make_topics_result     result = f.result()   File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 425, in result     return self.__get_result()   File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 384, in __get_result     raise self._exception cimpl.KafkaException: KafkaError{code=_TIMED_OUT,val=-185,str="Failed while waiting for controller: Local: Timed out"}  During handling of the above exception, another exception occurred:  Traceback (most recent call last):   File "/opt/seagate/cortx/sspl/low-level/files/opt/seagate/sspl/setup/sspl_config.py", line 147, in create_message_types     partitions=1)   File "/usr/lib/python3.6/site-packages/cortx/utils/message_bus/message_bus_client.py", line 63, in register_message_type     partitions)   File "/usr/lib/python3.6/site-packages/cortx/utils/message_bus/message_bus.py", line 81, in register_message_type     partitions)   File "/usr/lib/python3.6/site-packages/cortx/utils/message_bus/message_broker_collection.py", line 219, in register_message_type     self._task_status(created_message_types, method='register_message_type')   File "/usr/lib/python3.6/site-packages/cortx/utils/message_bus/message_broker_collection.py", line 161, in _task_status     "Admin operation fails for %s. %s", method, e) cortx.utils.message_bus.error.MessageBusError: error(4352): Admin operation fails for register_message_type. KafkaError{code=_TIMED_OUT,val=-185,str="Failed while waiting for controller: Local: Timed out"} Aug 11 19:31:56 sspl-setup[16077]: ERROR Failed in SSPL Setup Interface. ERROR: SetupError(1): MessageBusError:error(4352): Admin operation fails for register_message_type. KafkaError{code=_TIMED_OUT,val=-185,str="Failed while waiting for controller: Local: Timed out"} () (sspl_setup:616) Traceback (most recent call last):   File "/usr/lib/python3.6/site-packages/cortx/utils/message_bus/message_broker_collection.py", line 156, in _task_status     task.result()  # The result itself is None   File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 432, in result     return self.__get_result()   File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 384, in __get_result     raise self._exception   File "/usr/local/lib64/python3.6/site-packages/confluent_kafka/admin/__init__.py", line 225, in _make_topics_result     result = f.result()   File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 425, in result     return self.__get_result()   File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 384, in __get_result     raise self._exception cimpl.KafkaException: KafkaError{code=_TIMED_OUT,val=-185,str="Failed while waiting for controller: Local: Timed out"}  During handling of the above exception, another exception occurred:  Traceback (most recent call last):   File "/opt/seagate/cortx/sspl/low-level/files/opt/seagate/sspl/setup/sspl_config.py", line 147, in create_message_types     partitions=1)   File "/usr/lib/python3.6/site-packages/cortx/utils/message_bus/message_bus_client.py", line 63, in register_message_type     partitions)   File "/usr/lib/python3.6/site-packages/cortx/utils/message_bus/message_bus.py", line 81, in register_message_type     partitions)   File "/usr/lib/python3.6/site-packages/cortx/utils/message_bus/message_broker_collection.py", line 219, in register_message_type     self._task_status(created_message_types, method='register_message_type')   File "/usr/lib/python3.6/site-packages/cortx/utils/message_bus/message_broker_collection.py", line 161, in _task_status     "Admin operation fails for %s. %s", method, e) cortx.utils.message_bus.error.MessageBusError: error(4352): Admin operation fails for register_message_type. KafkaError{code=_TIMED_OUT,val=-185,str="Failed while waiting for controller: Local: Timed out"}  During handling of the above exception, another exception occurred:  Traceback (most recent call last):   File "/opt/seagate/cortx/sspl/bin/sspl_setup", line 613, in main     command.process()   File "/opt/seagate/cortx/sspl/bin/sspl_setup", line 232, in process     self.sspl_config.process()   File "/opt/seagate/cortx/sspl/low-level/files/opt/seagate/sspl/setup/sspl_config.py", line 110, in process     self.create_message_types()   File "/opt/seagate/cortx/sspl/low-level/files/opt/seagate/sspl/setup/sspl_config.py", line 153, in create_message_types     raise SetupError(1, msg) files.opt.seagate.sspl.setup.setup_error.SetupError: SetupError(1): MessageBusError:error(4352): Admin operation fails for register_message_type. KafkaError{code=_TIMED_OUT,val=-185,str="Failed while waiting for controller: Local: Timed out"} () /opt/seagate/cortx/sspl/bin/sspl_setup             [ -h|--help ]             [ post_install --config [<global_config_url>] ]             [ init --config [<global_config_url>] ]             [ config --config [<global_config_url>] ]             [ test --config [<global_config_url>] --plan [sanity|alerts|dev_sanity|full|performance|scalability|regression] ]             [ reset --config [<global_config_url>] ]             [ join_cluster --nodes [<nodes>] ]             [ manifest_support_bundle [<id>] [<path>] ]             [ support_bundle [<id>] [<path>] ]             [ check ]             [ cleanup [--pre-factory]]               - CMD: /opt/seagate/cortx/sspl/bin/sspl_setup config --config yaml:///opt/seagate/cortx/sspl/conf/temp/config.1-node
ERROR: Deployment is failed.
```
RPMs are installed successfully:
```sh
[root@cmu cortx-monitor]#       rpm -qa | grep sspl
cortx-sspl-cli-2.0.0-1_git8c929713.el7.noarch
cortx-libsspl_sec-debuginfo-2.0.0-1_git8c929713.el7.x86_64
cortx-sspl-2.0.0-1_git8c929713.el7.noarch
cortx-libsspl_sec-method_none-2.0.0-1_git8c929713.el7.x86_64
cortx-libsspl_sec-devel-2.0.0-1_git8c929713.el7.x86_64
cortx-libsspl_sec-2.0.0-1_git8c929713.el7.x86_64
cortx-sspl-test-2.0.0-1_git8c929713.el7.noarch
cortx-libsspl_sec-method_pki-2.0.0-1_git8c929713.el7.x86_64
```

Kafka is running well:
```sh
[root@cmu cortx-monitor]# systemctl status kafka
● kafka.service - Apache Kafka server (broker)
   Loaded: loaded (/etc/systemd/system/kafka.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2021-08-11 19:31:02 UTC; 9min ago
     Docs: http://kafka.apache.org/documentation.html
 Main PID: 15562 (java)
   CGroup: /system.slice/kafka.service
           └─15562 java -Xmx1G -Xms1G -server -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:InitiatingHeapOccupancyPercent=35 -XX:+ExplicitGCIn...

Aug 11 19:31:04 cmu kafka-server-start.sh[15562]: [2021-08-11 19:31:04,669] INFO [ExpirationReaper-0-AlterAcls]: Starting (kafka.se...Reaper)
Aug 11 19:31:04 cmu kafka-server-start.sh[15562]: [2021-08-11 19:31:04,684] INFO [/config/changes-event-process-thread]: Starting (...Thread)
Aug 11 19:31:04 cmu kafka-server-start.sh[15562]: [2021-08-11 19:31:04,693] INFO [SocketServer brokerId=0] Starting socket server a...Server)
Aug 11 19:31:04 cmu kafka-server-start.sh[15562]: [2021-08-11 19:31:04,696] INFO [SocketServer brokerId=0] Started data-plane accep...Server)
Aug 11 19:31:04 cmu kafka-server-start.sh[15562]: [2021-08-11 19:31:04,698] INFO [SocketServer brokerId=0] Started socket server ac...Server)
Aug 11 19:31:04 cmu kafka-server-start.sh[15562]: [2021-08-11 19:31:04,701] INFO Kafka version: 2.7.0 (org.apache.kafka.common.util...Parser)
Aug 11 19:31:04 cmu kafka-server-start.sh[15562]: [2021-08-11 19:31:04,701] INFO Kafka commitId: 448719dc99a19793 (org.apache.kafka...Parser)
Aug 11 19:31:04 cmu kafka-server-start.sh[15562]: [2021-08-11 19:31:04,701] INFO Kafka startTimeMs: 1628710264698 (org.apache.kafka...Parser)
Aug 11 19:31:04 cmu kafka-server-start.sh[15562]: [2021-08-11 19:31:04,702] INFO [KafkaServer id=0] started (kafka.server.KafkaServer)
Aug 11 19:31:04 cmu kafka-server-start.sh[15562]: [2021-08-11 19:31:04,781] INFO [broker-0-to-controller-send-thread]: Recorded new...Thread)
Hint: Some lines were ellipsized, use -l to show in full.
```

Content of ~/template_values.1-node.txt:
```sh
[root@cmu cortx-monitor]# cat ~/template_values.1-node.txt
# 1-node config variable
TMPL_CLUSTER_ID=CC01
TMPL_NODE_ID=SN01
TMPL_RACK_ID=RC01
TMPL_SITE_ID=DC01
TMPL_MACHINE_ID=dadec1eaa48646ff825eb1b3e026293f
TMPL_HOSTNAME=cmu
TMPL_NODE_NAME=srvnode-1
TMPL_SERVER_NODE_TYPE=VM
TMPL_MGMT_INTERFACE=eth0
TMPL_MGMT_PUBLIC_FQDN=localhost
TMPL_DATA_PRIVATE_FQDN=localhost
TMPL_DATA_PRIVATE_INTERFACE=
TMPL_DATA_PUBLIC_FQDN=localhost
TMPL_DATA_PUBLIC_INTERFACE=
TMPL_BMC_IP=
TMPL_BMC_USER=
TMPL_BMC_SECRET="gAAAAABhFB_utNTj6iS4qCxciNNAdSf_CccpKoCVQ-VPh8xjQFRcX-y1sD7U0BSoqeDEp-k0ju0HIAsyFFYMQPLfygD2mWBbtg=="

TMPL_ENCLOSURE_ID=enc_0449364d92b2ba3915fcd8416014cff7
TMPL_ENCLOSURE_NAME=enclosure-1
TMPL_ENCLOSURE_TYPE=VM
TMPL_PRIMARY_CONTROLLER_IP=127.0.0.1
TMPL_PRIMARY_CONTROLLER_PORT=28200
TMPL_SECONDARY_CONTROLLER_IP=127.0.0.1
TMPL_SECONDARY_CONTROLLER_PORT=28200
TMPL_CONTROLLER_USER=manage
TMPL_CONTROLLER_SECRET="gAAAAABhFB_uqNKFFbR3EOZGhvdblOrxLLvI21ucOd1KYKac6Rx2ShLM9TIUHYD3saL1AUJfVVR_k7iZKEgfk1qkjX9llkD8ow=="
TMPL_CONTROLLER_TYPE=Gallium
```

ifconfig:
```sh
[root@cmu cortx-monitor]# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.187.128  netmask 255.255.255.0  broadcast 192.168.187.255
        inet6 fe80::20c:29ff:fe68:4ab9  prefixlen 64  scopeid 0x20<link>
        ether 00:0c:29:68:4a:b9  txqueuelen 1000  (Ethernet)
        RX packets 727700  bytes 1021031035 (973.7 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 249994  bytes 16614552 (15.8 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 1969  bytes 169695 (165.7 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1969  bytes 169695 (165.7 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

storage partition:
```sh
[root@cmu cortx-monitor]# lsblk
NAME   MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
sda      8:0    0  40G  0 disk
└─sda1   8:1    0  40G  0 part /
```

machine id:
```sh
[root@cmu cortx-monitor]# cat /etc/machine-id
dadec1eaa48646ff825eb1b3e026293f
```

I don't know how to get the enclosure id, so I use the default value.
Thanks!

cc: @cdeshmukh

**Comment by thavanathan** [comment]
Can you please try following?
```
./sspl_dev_deploy --cleanup
./sspl_dev_deploy --prereq -L /root/MYRPMS
./sspl_dev_deploy --deploy -L /root/MYRPMS --variable_file /root/template_values.1-node.txt --storage_type RBOD --server_type HW
```

**Comment by daniarherikurniawan** [comment]
Thanks @thavanathan !
It solved the problem
```sh
Complete!
INFO: Done installing SSPL RPMS.
INFO: Executing command: '/opt/seagate/cortx/utils/bin/utils_setup post_install --config yaml:///opt/seagate/cortx/sspl/conf/temp/post-install.1-node'
INFO: Executing command: '/opt/seagate/cortx/sspl/bin/sspl_setup post_install --config yaml:///opt/seagate/cortx/sspl/conf/temp/post-install.1-node'
INFO: Executing command: '/opt/seagate/cortx/sspl/bin/sspl_setup prepare --config yaml:///opt/seagate/cortx/sspl/conf/temp/prepare.1-node'
INFO: Executing command: '/opt/seagate/cortx/utils/bin/utils_setup config --config yaml:///opt/seagate/cortx/sspl/conf/temp/config.1-node'
INFO: Executing command: '/opt/seagate/cortx/sspl/bin/sspl_setup config --config yaml:///opt/seagate/cortx/sspl/conf/temp/config.1-node'
INFO: Executing command: '/opt/seagate/cortx/utils/bin/utils_setup init'
INFO: Executing command: '/opt/seagate/cortx/sspl/bin/sspl_setup init --config yaml:///opt/seagate/cortx/sspl/conf/temp/init.1-node'
INFO: Deployment is successful !!
```
